NumPy

1.Create a 1D array from a list.


In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)


[1 2 3 4 5]


2. Create a 3x3 array of zeros.


In [34]:
arr=np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Create a 2x2 array of ones.

In [35]:
arr=np.ones((2,2))
print(arr)

[[1. 1.]
 [1. 1.]]


4. Generate array from 0 to 10 (exclusive).

In [36]:
arr = np.arange(0, 10)
print("\nArray from 0 to 10 (exclusive):", arr)



Array from 0 to 10 (exclusive): [0 1 2 3 4 5 6 7 8 9]


5. Create 5 evenly spaced numbers between 0 and 1.


In [37]:
arr = np.linspace(0, 1, 5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


6. Create a 4x4 identity matrix.

In [38]:
arr=np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


7. Reshape 1D array to 2D.

In [39]:
arr = np.arange(6)
reshaped_arr = arr.reshape(2, 3)
print("\nReshaped 1D array to 2D:\n", reshaped_arr)


Reshaped 1D array to 2D:
 [[0 1 2]
 [3 4 5]]


8. Get the shape and dtype of an array.

In [40]:
arr=np.array([1,2,3,4])
print("\nShape:", arr.shape)
print("Dtype:", arr.dtype)


Shape: (4,)
Dtype: int64


9. Reverse a NumPy array.

In [41]:
arr=np.array([1,2,3,4,5,6])
rev=arr[::-1]
print(rev)

[6 5 4 3 2 1]


10. Extract even numbers from an array.

In [42]:
arr2=np.array([1,2,3,4,5])
even_numbers = arr2[arr2 % 2 == 0]
print("\nEven numbers:", even_numbers)


Even numbers: [2 4]


11. Find the max in each row.

In [43]:
arr = np.array([[1, 5, 3], [7, 2, 8]])
max_in_rows = np.max(arr, axis=1)
print("\nMax in each row:", max_in_rows)


Max in each row: [5 8]


12. Compute the mean, std, and median of an array.


In [44]:
arr4 = np.array([1, 2, 3, 4, 5])
print("\nMean:", np.mean(arr4))
print("Std:", np.std(arr4))
print("Median:", np.median(arr4))


Mean: 3.0
Std: 1.4142135623730951
Median: 3.0


13. Stack two arrays vertically.

In [45]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c= np.vstack((a, b))
print(c)

[[1 2 3]
 [4 5 6]]


14. Stack two arrays horizontally.

In [46]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c= np.hstack((a, b))
print(c)

[1 2 3 4 5 6]


15. Stack two arrays horizontally.


In [47]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c= np.hstack((a, b))
print(c)

[1 2 3 4 5 6]


16. Find the unique values and their counts.


In [48]:

arr5 = np.array([1, 2, 2, 3, 3, 3])
unique, counts = np.unique(arr5, return_counts=True)
print("\nUnique values:", unique)
print("Counts:", counts)


Unique values: [1 2 3]
Counts: [1 2 3]


17. Replace NaN with column means.


18. Get index of min and max values.


In [49]:
arr7 = np.array([3, 1, 5, 2])
print("\nIndex of min:", np.argmin(arr7))
print("Index of max:", np.argmax(arr7))


Index of min: 1
Index of max: 2


19. Create a 3D array of random integers.



In [50]:
arr8 = np.random.randint(0, 10, size=(2, 3, 4))
print("\n3D array of random integers:\n", arr8)


3D array of random integers:
 [[[9 5 0 6]
  [4 6 7 3]
  [9 7 5 9]]

 [[6 1 9 2]
  [5 1 0 3]
  [0 5 8 1]]]


20. Use np.where() to replace values


In [51]:
arr9 = np.array([1, 2, 3, 4, 5])
replaced_arr = np.where(arr9 > 3, 0, arr9)
print("\nValues >3 replaced with 0:", replaced_arr)


Values >3 replaced with 0: [1 2 3 0 0]


Pandas

1. Create a Series using a Python list.


In [3]:

#1. Create a Series using a Python list.
import pandas as pd
data = [1, 2, 3, 4, 5]
series = pd.Series(data)
print(series)

#OR OR 
series1 = pd.Series([10, 20, 30])
print("\nSeries from list:\n", series1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

Series from list:
 0    10
1    20
2    30
dtype: int64


2. Create a Series with custom string indices.




In [7]:
series2 = pd.Series([100, 200, 300], index=['a', 'b', 'c'])
print(series2)

a    100
b    200
c    300
dtype: int64


3. Create a Series from a dictionary.


In [13]:
data = {'x': 10, 'y': 20, 'z': 30}
series3 = pd.Series(data)
print(series3)

x    10
y    20
z    30
dtype: int64


4. Access first 3 elements of a Series.


In [18]:
series=pd.Series([10,20,30,40,50,60,70])
print("\nFirst 3 elements of series1:\n", series.head(3))


First 3 elements of series1:
 0    10
1    20
2    30
dtype: int64


5. Filter Series elements greater than 50.



In [21]:
series3=pd.Series([10,20,30,40,50,60,70])
filtered = series3[series3 > 50]
print("\nFiltered Series (values >15):\n", filtered)


Filtered Series (values >15):
 5    60
6    70
dtype: int64


6. Add two Series with different indices.



In [34]:
series4 = pd.Series([1, 2, 3], index=['a', 'b', 'c'])
series5 = pd.Series([4, 5], index=['b', 'c'])
sum_series = series4.add(series5, fill_value=0)
print(sum_series) #addtion acording to index

a    1.0
b    6.0
c    8.0
dtype: float64



7. Multiply a Series by a scalar.


In [29]:
print(series4 * 2) #as previusly we have created seriese4 so it will automatically use that or we can create new one also 

#or or 
series = pd.Series([0, 5, 10], index=['a', 'b', 'c'])
print("\nSeries4 multiplied by 2:\n", series * 2)

a    2
b    4
c    6
dtype: int64

Series4 multiplied by 2:
 a     0
b    10
c    20
dtype: int64


8. Use .multiply() method to multiply with scalar.


In [30]:
print("\nSeries4 multiplied by 3 using .multiply():\n", series4.multiply(3))


Series4 multiplied by 3 using .multiply():
 a    3
b    6
c    9
dtype: int64


10. Sort Series by values descending.


In [35]:
print(series4.sort_values(ascending=False))


Series4 sorted descending:
 c    3
b    2
a    1
dtype: int64


11. Sort Series by index.


In [39]:
series4.sort_index() #direct or by using a print statement . Its better to use print like following 

# print("\nSeries4 sorted by index:\n", series4.sort_index())

a    1
b    2
c    3
dtype: int64

12. Check for null values.



In [29]:
series6 = pd.Series([1, np.nan, 3])
print("\nCheck for null values:\n", series6.isnull())


Check for null values:
 0    False
1     True
2    False
dtype: bool


14. Concatenate two Series using concat().


In [9]:
s1=pd.Series([10,20,30,40,50,60,70])
s2=pd.Series([1,22,3,4,5,6,7])
concat_series = pd.concat([s1,s2])
print(concat_series)

0    10
1    20
2    30
3    40
4    50
5    60
6    70
0     1
1    22
2     3
3     4
4     5
5     6
6     7
dtype: int64


15. Concatenate two Series using append().


In [15]:
# s1=pd.Series([10,20,30,40,50,60,70])
# s2=pd.Series([1,22,3,4,5,6,7])
# append_series = s1.append(s2)
# print("\nAppended Series:\n", append_series)

# Importing pandas as pd
import pandas as pd

# Creating the first Dataframe using dictionary
df1 = pd.DataFrame({"a":[1, 2, 3, 4],"b":[5, 6, 7, 8]})

# Creating the Second Dataframe using dictionary
df2 = pd.DataFrame({"a":[1, 2, 3],"b":[5, 6, 7]})

# to append df2 at the end of df1 dataframe
print(df1.append(df2))

AttributeError: 'DataFrame' object has no attribute 'append'

16. Retrieve first 5 elements using .head()



In [18]:
print("\nFirst 5 elements:\n", concat_series.head(5))


First 5 elements:
 0    10
1    20
2    30
3    40
4    50
dtype: int64


17. Retrieve last 5 elements using .tail()


In [19]:
print("\nLast 5 elements:\n", concat_series.tail(5))


Last 5 elements:
 2    3
3    4
4    5
5    6
6    7
dtype: int64


18. Convert Series to DataFrame.


In [24]:
series=pd.Series([11,22,33,44,55])
df = series.to_frame(name='Values')
print("\nSeries as DataFrame:\n", df)


Series as DataFrame:
    Values
0      11
1      22
2      33
3      44
4      55


19. Replace NaN with 0.


In [31]:
print("\nSeries6 with NaN replaced with 0:\n", series6.fillna(0)) 


Series6 with NaN replaced with 0:
 0    1.0
1    0.0
2    3.0
dtype: float64


20. Drop missing values.


In [32]:
print("\nSeries6 without NaN:\n", series6.dropna())


Series6 without NaN:
 0    1.0
2    3.0
dtype: float64


21. Check Series data type.



In [35]:
print("\nData type of Series4:", series4.dtype)


Data type of Series4: int64
